### ISSUE TITLE
Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0

### ISSUE THREAD

**Issue by aJoohongKim** [aws-samples/aws-alien-attack#14]
I follow the instruction on https://catalog.us-east-1.prod.workshops.aws/v2/workshops/fc36cb5a-de1b-403f-84dd-cc824390c548/en-US/20-environment-setup/24-deploy-the-backend

If I am working with aws-cli v1, I will have the following error:
> This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
>(Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0)

If I am working with aws-cli v2, I will have the following error:
>  The security token included in the request is invalid

Also if aws-cli v2 is used, the line 21 in update-upgrade-install.sh should be update 
`
npm install -g aws-cdk@1.126.0
`

**Comment by fabianmartins** [comment]
Sorry for the issue. As you noticed, I forgot to update `update-upgrade-install.sh`. 
Fixed with the commit [776da4e](https://github.com/aws-samples/aws-alien-attack/commit/776da4ed69a0e4680da7878180c6c05ef256c5f0).
If you have a running environment, just run `source config.sh` again, from the `infrastructure` folder, and it will fix your environment.

The `config.sh` script must be run again not only to update your CDK version, but also to upgrade the CDK bootstrap infrastructure within your AWS account/region.
